version: '3'

services:
  Frontend:
    image: csw1511/neureka-frontend:latest
    ports:
      - "5174:5174"
    restart: always

  Backend:
    image: csw1511/neureka-backend:latest
    ports:
      - "8080:8080"
    restart: always

  Python:
    image: csw1511/neureka-python:latest
    ports:
      - "8000:8000"
    restart: always
  
  redis:
    image: 170a1e90f843
    ports:
      - "6379:6379"
    restart: always
